alias latest='ls -fd *(om[1])'
alias vnc='vncviewer -DesktopSize 1024x600'
alias xclip='xclip -selection c'
alias gedit='gedit &>/dev/null'
alias gdebi-gtk='gdebi-gtk &>/dev/null'
alias irssi='screen -D -RR -S irssi irssi'
