alias latest='echo *(om[1])'
alias vnc='vncviewer -DesktopSize 1024x600'
alias xclip='xclip -selection c'
alias gedit='gedit &>/dev/null'
alias gdebi-gtk='gdebi-gtk &>/dev/null'
alias caffeine='echo -n "Keeping display awake "; while sleep 60; do xdotool keydown Shift_L keyup Shift_L; echo -n "."; done'
alias doch='sudo $(fc -ln -1)'
alias irssi='screen -D -RR -S irssi irssi'
